#ifndef LAB2_CONSTANTS_H
#define LAB2_CONSTANTS_H

#define FILE_NAME_LEN_MAX            4096
#define NUM_BYTES_TO_SEND            1048576
#define SPEED_PRINT_INTERVAL_SECONDS 1.5f

#endif //LAB2_CONSTANTS_H
